name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Build and run tests using Dockerfile.dev
      - run: docker build -t surfdatasolutions/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true surfdatasolutions/react-test npm test

  deploy:
    needs: test  # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      # Build production image using main Dockerfile
      - run: docker build -t surfdatasolutions/react-prod .
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env-1
          existing_bucket_name: elasticbeanstalk-us-east-2-637423329874
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
  


